#!/bin/sh
for i in `seq 5`
do
  echo Step $i
  echo " - go to 0"
  mosquitto_pub -h 192.168.0.82 -t board05/motor1/set -m 0
  sleep 155
  echo " - go to +60K"
  mosquitto_pub -h 192.168.0.82 -t board05/motor1/set -m 60000
  sleep 155
done
