#!/bin/sh
COMMAND=""
while /bin/true; do
    COMMAND=$(whiptail --title "Remote control tool" --default-item "$COMMAND" \
        --menu "The device is controlled over MQTT\nA command is a specific message to the specified topic" 17 72 8 \
            "dev/board05/led/set 1"         "        Turn LED on" \
            "dev/board05/led/set 0"         "        Turn LED off" \
        3>&2 2>&1 1>&3)
    if [ $? -gt 0 ]; then
        break
    fi
    TOPIC=$(echo $COMMAND | cut -f1 -d" ")
    MESSAGE=$(echo $COMMAND | cut -f2 -d" ")
    mosquitto_pub -h 192.168.0.82 -t $TOPIC -m $MESSAGE
done

