#!/bin/sh
HOST="192.168.0.82"
SUBSCRIBE="#"
#mosquitto_sub -h "$HOST" -t "$SUBSCRIBE" -v
mosquitto_sub -h "$HOST" -t "$SUBSCRIBE" -F "\e[34m@H:@M:@S\e[0m topic=\e[32m%-24t\e[0m message=\e[36m%p\e[0m"
